-- ====================================================================
-- DŽEMAT VREOCA - SUPABASE BAZA PODATAKA
-- Kopirajte i pokrenite ovaj SQL u Supabase SQL Editoru
-- ====================================================================

-- 1. Tabela za prijave u mekteb
CREATE TABLE IF NOT EXISTS mekteb_prijave (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_name TEXT NOT NULL,
  child_name TEXT NOT NULL,
  birth_year INTEGER NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  group_level TEXT NOT NULL,
  status TEXT DEFAULT 'na_cekanju', -- 'na_cekanju', 'upisano', 'arhivirano'
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabela za pitanja imamu i javne odgovore
CREATE TABLE IF NOT EXISTS pitanja_imamu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_name TEXT DEFAULT 'Džematlija',
  sender_contact TEXT,
  question TEXT NOT NULL,
  answer TEXT,
  is_published BOOLEAN DEFAULT FALSE,
  category TEXT DEFAULT 'Opće', -- 'Namazi', 'Post', 'Porodica', 'Ahlak', 'Opće'
  answered_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabela za tekstualne hutbe
CREATE TABLE IF NOT EXISTS hutbe (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date_str TEXT NOT NULL,
  category TEXT NOT NULL,
  summary TEXT NOT NULL,
  content TEXT NOT NULL,
  author TEXT DEFAULT 'Imam džemata Vreoca',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Uključivanje Row Level Security (RLS)
ALTER TABLE mekteb_prijave ENABLE ROW LEVEL SECURITY;
ALTER TABLE pitanja_imamu ENABLE ROW LEVEL SECURITY;
ALTER TABLE hutbe ENABLE ROW LEVEL SECURITY;

-- Politike pristupa (Policies):
-- Svi posjetioci mogu kreirati prijavu za mekteb
CREATE POLICY "Anonimno slanje prijave za mekteb" 
  ON mekteb_prijave FOR INSERT 
  WITH CHECK (true);

-- Svi posjetioci mogu postaviti pitanje
CREATE POLICY "Anonimno slanje pitanja imamu" 
  ON pitanja_imamu FOR INSERT 
  WITH CHECK (true);

-- Svi posjetioci mogu čitati samo objavljena pitanja
CREATE POLICY "Javno čitanje objavljenih pitanja" 
  ON pitanja_imamu FOR SELECT 
  USING (is_published = true);

-- Svi posjetioci mogu čitati sve hutbe
CREATE POLICY "Javno čitanje hutbi" 
  ON hutbe FOR SELECT 
  USING (true);

-- Inicijalni podaci za hutbe (Seed)
INSERT INTO hutbe (title, date_str, category, summary, content, author)
VALUES 
(
  'Vrijednost zajedništva i džemata u islamu',
  '28.08.2026.',
  'Zajedništvo',
  'O važnosti očuvanja sloge među komšijama, džematskog jedinstva i podršci onima u potrebi.',
  'Hvala Allahu, Gospodaru svih svjetova, Koji nas je stvorio u najljepšem obliku i Koji nas poziva na slogu i međusobno potpomaganje. Draga braćo u islamu, džemat je snaga svakog vjernika. Poslanik, s.a.v.s., je rekao: "Allahova ruka je nad džematom." Čuvajmo naš džemat, pomažimo se u dobru i budimo podrška jedni drugima u svakodnevnom životu.',
  'Imam džemata Vreoca'
),
(
  'Odgoj djece u vremenu izazova',
  '21.08.2026.',
  'Porodica i odgoj',
  'Uloga roditelja i mekteba u formiranju čestite i obrazovane omladine pod okriljem islamskih vrijednosti.',
  'U ime Allaha, Milostivog, Samilosnog. Naša djeca su emanet koji nam je povjeren. Najveći poklon koji roditelj može dati svom djetetu jeste lijep ahlak, znanje i ljubav prema Stvoritelju. Mekteb je sigurna luka gdje naša djeca uče istinske vrijednosti.',
  'Imam džemata Vreoca'
);

-- Inicijalni podaci za javna pitanja i odgovore (Seed)
INSERT INTO pitanja_imamu (sender_name, sender_contact, question, answer, is_published, category, answered_at)
VALUES
(
  'Džematlija',
  'vreoca@medzlis-sarajevo.ba',
  'Kako se naklanjavaju propušteni namazi iz opravdanih razloga?',
  'Propušteni namaz se treba naklanjati čim se čovjek sjeti ili prestane razlog zbog kojeg je namaz propušten. Naklanjava se samo farz (izuzev sabahskog namaza gdje se do podne naklanjava i sunnet i farz). Nijet se donosi za naklanjavanje onog namaza koji je propušten.',
  true,
  'Namazi',
  timezone('utc'::text, now())
),
(
  'Roditelj iz Vreoca',
  'vreoca@medzlis-sarajevo.ba',
  'Kada počinje upis u mekteb i koja je starosna granica za početni nivo?',
  'Upis u mekteb u našem džematu Vreoca otvoren je za svu djecu uzrasta od 6 godina pa naviše. Nastava se odvija subotom i nedjeljom, a grupe su podijeljene po uzrastu i nivou znanja (Početnici, Sufara, Kur''an i hifz). Prijavu možete izvršiti i putem online formulara na našoj stranici.',
  true,
  'Mekteb',
  timezone('utc'::text, now())
);
