-- ====================================================================
-- DŽEMAT VREOCA - SUPABASE BAZA PODATAKA (KOMPLETNA ŠEMA)
-- Upute: Označite sav tekst (Ctrl + A) u Supabase SQL Editoru i kliknite RUN
-- ====================================================================

-- 1. Tabela za prijave u mekteb
CREATE TABLE IF NOT EXISTS mekteb_prijave (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_name TEXT,                    -- LEGACY: staro polje, zadržano za kompatibilnost
  parent_name_father TEXT NOT NULL,    -- Ime i prezime oca
  parent_name_mother TEXT NOT NULL,    -- Ime i prezime majke
  child_name TEXT NOT NULL,
  birth_year INTEGER NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  group_level TEXT NOT NULL,
  school_grade TEXT,                   -- Razred u školi (npr. "5. razred OŠ", "II razred SŠ")
  school_name TEXT,                    -- Naziv škole (opciono)
  status TEXT DEFAULT 'na_cekanju',    -- 'na_cekanju', 'upisano', 'arhivirano'
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabela za pitanja imamu i javne odgovore
CREATE TABLE IF NOT EXISTS pitanja_imamu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_name TEXT DEFAULT 'Džematlija',
  sender_contact TEXT NOT NULL,
  question TEXT NOT NULL,
  answer TEXT,
  is_published BOOLEAN DEFAULT FALSE,
  category TEXT DEFAULT 'Opće', -- 'Namazi', 'Post', 'Porodica', 'Ahlak', 'Opće', 'Mekteb'
  answered_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabela za tekstualne hutbe
CREATE TABLE IF NOT EXISTS hutbe (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date_str TEXT NOT NULL,
  category TEXT NOT NULL,
  summary TEXT NOT NULL,
  content TEXT NOT NULL,
  author TEXT DEFAULT 'Imam džemata Vreoca',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tabela za džematske aktivnosti i aktuelnosti
CREATE TABLE IF NOT EXISTS aktivnosti (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date_str TEXT NOT NULL,
  time_str TEXT,
  location TEXT DEFAULT 'Džamija Vreoca',
  category TEXT NOT NULL DEFAULT 'Džemat', -- 'Edukacija', 'Humanitarno', 'Omladina', 'Džemat', 'Ramazan'
  summary TEXT NOT NULL,
  description TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Tabela za pretplatnike na newsletter / obavijesti džemata
CREATE TABLE IF NOT EXISTS newsletter_pretplatnici (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Uključivanje Row Level Security (RLS)
ALTER TABLE mekteb_prijave ENABLE ROW LEVEL SECURITY;
ALTER TABLE pitanja_imamu ENABLE ROW LEVEL SECURITY;
ALTER TABLE hutbe ENABLE ROW LEVEL SECURITY;
ALTER TABLE aktivnosti ENABLE ROW LEVEL SECURITY;
ALTER TABLE newsletter_pretplatnici ENABLE ROW LEVEL SECURITY;

-- Sigurno uklanjanje postojećih politika prije kreiranja (zaštita od duplikata)
DROP POLICY IF EXISTS "Anonimno slanje prijave za mekteb" ON mekteb_prijave;
DROP POLICY IF EXISTS "Admin upravljanje mekteb prijavama" ON mekteb_prijave;
DROP POLICY IF EXISTS "Anonimno slanje pitanja imamu" ON pitanja_imamu;
DROP POLICY IF EXISTS "Javno čitanje objavljenih pitanja" ON pitanja_imamu;
DROP POLICY IF EXISTS "Admin upravljanje pitanjima" ON pitanja_imamu;
DROP POLICY IF EXISTS "Javno čitanje hutbi" ON hutbe;
DROP POLICY IF EXISTS "Admin upravljanje hutbama" ON hutbe;
DROP POLICY IF EXISTS "Javno čitanje aktivnosti" ON aktivnosti;
DROP POLICY IF EXISTS "Admin upravljanje aktivnostima" ON aktivnosti;
DROP POLICY IF EXISTS "Anonimna prijava na newsletter" ON newsletter_pretplatnici;
DROP POLICY IF EXISTS "Admin upravljanje newsletterom" ON newsletter_pretplatnici;

-- Kreiranje politika pristupa:
CREATE POLICY "Anonimno slanje prijave za mekteb" 
  ON mekteb_prijave FOR ALL 
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Anonimno slanje pitanja imamu" 
  ON pitanja_imamu FOR ALL 
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Javno čitanje hutbi" 
  ON hutbe FOR ALL 
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Javno čitanje aktivnosti" 
  ON aktivnosti FOR ALL 
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Anonimna prijava na newsletter" 
  ON newsletter_pretplatnici FOR ALL 
  USING (true)
  WITH CHECK (true);

-- ====================================================================
-- INICIJALNI PODACI (SEED)
-- ====================================================================

-- Hutbe
INSERT INTO hutbe (title, date_str, category, summary, content, author)
VALUES 
(
  'Vrijednost zajedništva i džemata u islamu',
  '28.08.2026.',
  'Zajedništvo',
  'O važnosti očuvanja sloge među komšijama, džematskog jedinstva i podršci onima u potrebi.',
  'Hvala Allahu, Gospodaru svih svjetova, Koji nas je stvorio u najljepšem obliku i Koji nas poziva na slogu i međusobno potpomaganje. Draga braćo u islamu, džemat je snaga svakog vjernika. Poslanik, s.a.v.s., je rekao: "Allahova ruka je nad džematom." Čuvajmo naš džemat Vreoca, pomažimo se u dobru i budimo podrška jedni drugima u svakodnevnom životu.',
  'Imam džemata Vreoca'
),
(
  'Odgoj djece u vremenu savremenih izazova',
  '21.08.2026.',
  'Porodica i odgoj',
  'Uloga roditelja i mekteba u formiranju čestite i obrazovane omladine pod okriljem islamskih vrijednosti.',
  'U ime Allaha, Milostivog, Samilosnog. Naša djeca su emanet koji nam je povjeren. Najveći poklon koji roditelj može dati svom djetetu jeste lijep ahlak, znanje i ljubav prema Stvoritelju. Mekteb je sigurna luka gdje naša djeca uče istinske vrijednosti.',
  'Imam džemata Vreoca'
);

-- Pitanja i odgovori
INSERT INTO pitanja_imamu (sender_name, sender_contact, question, answer, is_published, category, answered_at)
VALUES
(
  'Džematlija',
  'vreoca@medzlis-sarajevo.ba',
  'Kako se naklanjavaju propušteni namazi iz opravdanih razloga?',
  'Propušteni namaz se treba naklanjati čim se čovjek sjeti ili prestane razlog zbog kojeg je namaz propušten. Naklanjava se samo farz (izuzev sabahskog namaza gdje se do podne naklanjava i sunnet i farz). Nijet se donosi za naklanjavanje onog namaza koji je propušten.',
  true,
  'Namazi',
  timezone('utc'::text, now())
),
(
  'Roditelj iz Vreoca',
  'vreoca@medzlis-sarajevo.ba',
  'Kada počinje upis u mekteb i koja je starosna granica za početni nivo?',
  'Upis u mekteb u našem džematu Vreoca otvoren je za svu djecu uzrasta od 6 godina pa naviše. Nastava se odvija subotom i nedjeljom, a grupe su podijeljene po uzrastu i nivou znanja (Početnici, Sufara, Kur''an i hifz). Prijavu možete izvršiti i putem online formulara na našoj stranici.',
  true,
  'Mekteb',
  timezone('utc'::text, now())
);

-- Aktivnosti
INSERT INTO aktivnosti (title, date_str, time_str, location, category, summary, description)
VALUES
(
  'Tribina: Uloga porodice u savremenom društvu',
  '18.09.2026.',
  'Poslije akšam-namaza',
  'Divanhana džamije Vreoca',
  'Edukacija',
  'Edukativno predavanje i razgovor o očuvanju porodičnih vrijednosti uz gostujućeg predavača.',
  'Pozivamo sve džematlije i omladinu na redovnu džematsku tribinu. Nakon predavanja predviđeno je vrijeme za pitanja, diskusiju i druženje uz kahvu.'
),
(
  'Humanitarna akcija: Pomoć socijalno ugroženim porodicama',
  '25.09.2026.',
  'Tokom cijelog dana',
  'Džemat Vreoca',
  'Humanitarno',
  'Prikupljanje osnovnih životnih namirnica i higijenskih paketa za socijalno ugrožene sugrađane.',
  'Mreža mladih i Odbor džemata Vreoca organizuju prikupljanje paketa pomoći. Svi koji žele donirati mogu se javiti u prostorije džamije.'
);
